Add term_customizer gem and fix versioning of other modules
Platoniq/decidim-catencomu pull request #127
Opened 2024-10-09 14:21 UTC by HHassig

Added the term_customizer gem.
Set other gems to branch release/0.27-stable.
Needed to hard-code decidim-core, "0.27.5"

2024-10-10 08:51 UTC, davidbeig requested changes
In the test workflow we can see the following error

```
warning: parser/current is loading parser/ruby30, which recognizes 3.0.7-compliant syntax, but you are running 3.0.6.
```

It says that the parser gem recognizes the ruby 3.0.7 syntax but we are running v3.0.6. Following the updates in that gem i found this change. https://github.com/whitequark/parser/commit/31faa0aff60308647f2d81fef75bcd79414fe966 It looks like that change is the one responsible for this error.

Since parser is not a gem we are using, but one of our dependencies we have to check which one is it.

It's used by
- rubocop v1.28.2 - parser v3.1.0.0
- better_html v1.0.16 - parser >= v2.4
- erb_lint v0.0.37 - parser >= v2.7.1.4
- i18n-tasks v0.9.37 - parser >= v2.2.3.0
- rubocop-ast v1.32.3 - parser >= v.3.3.1.0 <--- this one seems to be the responsible

The version installed is: v3.3.5.0, so it has the change i pointed before.

The last version of rubocop-ast to have a dependency on a correct version of parser is v.1.31.2. You can see it [here](https://rubygems.org/gems/rubocop-ast/versions/1.31.2)

I think that by adding it to the test group in the Gemfile it will work fine.

Good job with the update of the test workflow :)

2024-10-14 10:32 UTC, davidbeig approved these changes

2024-10-15 09:12 UTC, fblupi requested changes

2024-10-15 09:12 UTC, fblupi commented on Gemfile
> +gem "decidim-core", DECIDIM_VERSION
You should not need this line

```suggestion
```

2024-10-15 09:12 UTC, fblupi commented on Gemfile
> +  gem "spring", "4.0"
Forcing a version for this gem could give us problems in the future, remove the version here.

```suggestion
  gem "spring"
```

2024-10-15 13:34 UTC, merged